# Generated by Django 5.2.17 on 2026-08-25 08:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(help_text='Unique batch identifier', max_length=50, unique=True)),
                ('supplier', models.CharField(max_length=200)),
                ('received_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PORK', 'Pork'), ('CHICKEN', 'Chicken'), ('BEEF', 'Beef'), ('LAMB', 'Lamb'), ('FISH', 'Fish'), ('OTHER', 'Other')], max_length=20)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('PIECE', 'Piece')], default='KG', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('FREEZER', 'Freezer'), ('THAW_AREA', 'Thaw Area'), ('DISPLAY', 'Display Case'), ('STORAGE', 'General Storage')], max_length=20)),
                ('capacity', models.PositiveIntegerField(default=50, help_text='Maximum packages')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in kilograms', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('packed_at', models.DateTimeField()),
                ('current_state', models.CharField(choices=[('PACKED', 'Packed'), ('FREEZING', 'Freezing'), ('FROZEN', 'Frozen'), ('READY_FOR_THAW', 'Ready For Thaw'), ('THAW_QUEUED', 'Thaw Queued'), ('THAWING', 'Thawing'), ('READY_FOR_SALE', 'Ready For Sale'), ('ON_DISPLAY', 'On Display'), ('REFREEZE_PENDING', 'Refreeze Pending'), ('PROCESSING', 'Processing'), ('DISCARDED', 'Discarded'), ('COMPLETED', 'Completed')], default='PACKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='inventory.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='inventory.product')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='inventory.storagelocation')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-packed_at'],
            },
        ),
    ]
