# Generated by Django 5.2.17 on 2026-08-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_temperature', models.DecimalField(decimal_places=2, help_text='Measured temperature in Celsius', max_digits=5)),
                ('target_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Expected target temperature', max_digits=5, null=True)),
                ('min_allowed', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed temperature', max_digits=5, null=True)),
                ('max_allowed', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed temperature', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='OK', max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Check'), ('SENSOR', 'IoT Sensor'), ('BLUETOOTH', 'Bluetooth Probe')], default='MANUAL', max_length=15)),
                ('recorded_by', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='inventory.storagelocation')),
            ],
            options={
                'verbose_name': 'Temperature Log',
                'verbose_name_plural': 'Temperature Logs',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
