# Generated by Django 5.2.17 on 2026-08-25 14:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_temperaturelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPlanningProfile',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='planning_profile', serialize=False, to='inventory.product')),
                ('avg_daily_usage_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average daily usage in kg', max_digits=8)),
                ('safety_stock_days', models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Minimum days of stock to maintain as safety buffer', max_digits=5)),
                ('target_coverage_days', models.DecimalField(decimal_places=1, default=Decimal('7.0'), help_text='Target number of days of stock to keep on hand', max_digits=5)),
                ('min_order_qty_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum quantity to prepare per batch', max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Planning Profile',
                'verbose_name_plural': 'Product Planning Profiles',
            },
        ),
    ]
