# Generated by Django 5.2.17 on 2026-08-25 19:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productplanningprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Package selling price (THB) — computed from weight × price/kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix used in barcode generation (e.g., 0051)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Purchase cost per kilogram (THB)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Fat in grams per 100g', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='kcalories',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Kilocalories per 100g', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Protein in grams per 100g', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Selling price per kilogram (THB)', max_digits=10),
        ),
        migrations.CreateModel(
            name='PriceChangeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('mode', models.CharField(default='manual', help_text='Change mode: manual, cost_margin, discount, price_per_kg, auto', max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The value used in calculation (margin %, discount %, or price/kg)', max_digits=10)),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='inventory.package')),
            ],
            options={
                'verbose_name': 'Price Change History',
                'verbose_name_plural': 'Price Change Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeSequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(help_text='Batch number this sequence belongs to', max_length=50)),
                ('supplier_id', models.PositiveIntegerField(default=0, help_text='Supplier ID for barcode composition')),
                ('last_sequence', models.PositiveIntegerField(default=0, help_text='Last used sequence number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_sequences', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Barcode Sequence',
                'verbose_name_plural': 'Barcode Sequences',
                'unique_together': {('product', 'batch_number', 'supplier_id')},
            },
        ),
    ]
