# Generated by Django 5.2.17 on 2026-08-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_package_selling_price_product_barcode_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='max_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed temperature in Celsius', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='min_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed temperature in Celsius', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='thaw_capacity',
            field=models.PositiveIntegerField(default=20, help_text='Maximum concurrent thaw operations (for THAW_AREA type)'),
        ),
    ]
