# Generated by Django 4.2.30 on 2026-08-28 18:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Unique batch identifier (e.g., B-20260829-001)', max_length=50, unique=True)),
                ('received_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='PORK, CHICKEN, etc.', max_length=20, unique=True)),
                ('name', models.CharField(help_text='English name', max_length=100)),
                ('name_thai', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Unique barcode', max_length=100, unique=True)),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in kilograms', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Package selling price (THB)', max_digits=10)),
                ('packed_at', models.DateTimeField()),
                ('current_state', models.CharField(choices=[('PACKED', 'Packed'), ('FREEZING', 'Freezing'), ('FROZEN', 'Frozen'), ('READY_FOR_THAW', 'Ready For Thaw'), ('THAW_QUEUED', 'Thaw Queued'), ('THAWING', 'Thawing'), ('READY_FOR_SALE', 'Ready For Sale'), ('ON_DISPLAY', 'On Display'), ('REFREEZE_PENDING', 'Refreeze Pending'), ('PROCESSING', 'Processing'), ('DISCARDED', 'Discarded'), ('COMPLETED', 'Completed')], default='PACKED', max_length=20)),
                ('loyverse_sku', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('loyverse_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('loyverse_variant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('loyverse_synced', models.BooleanField(default=False)),
                ('loyverse_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='inventory.batch')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-packed_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Product name (e.g., Pork Neck)', max_length=200)),
                ('name_thai', models.CharField(blank=True, default='', max_length=200)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('PIECE', 'Piece')], default='KG', max_length=10)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Purchase cost per kilogram (THB)', max_digits=10)),
                ('selling_price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Selling price per kilogram (THB)', max_digits=10)),
                ('barcode_prefix', models.CharField(blank=True, default='', help_text='Prefix used in barcode generation', max_length=20)),
                ('kcalories', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=8)),
                ('protein', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=8)),
                ('fat', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('FREEZER', 'Freezer'), ('THAW_AREA', 'Thaw Area'), ('DISPLAY', 'Display Case'), ('STORAGE', 'General Storage')], max_length=20)),
                ('capacity', models.PositiveIntegerField(default=50, help_text='Maximum packages')),
                ('thaw_capacity', models.PositiveIntegerField(default=20, help_text='Max concurrent thaw operations (for THAW_AREA)')),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed temperature (°C)', max_digits=5, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed temperature (°C)', max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('locations', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPlanningProfile',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='planning_profile', serialize=False, to='inventory.product')),
                ('avg_daily_usage_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average daily usage in kg', max_digits=8)),
                ('safety_stock_days', models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Minimum days of stock as safety buffer', max_digits=5)),
                ('target_coverage_days', models.DecimalField(decimal_places=1, default=Decimal('7.0'), help_text='Target days of stock to keep on hand', max_digits=5)),
                ('min_order_qty_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum quantity to prepare per batch', max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Planning Profile',
                'verbose_name_plural': 'Product Planning Profiles',
            },
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_temperature', models.DecimalField(decimal_places=2, help_text='Measured temperature (°C)', max_digits=5)),
                ('target_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_allowed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_allowed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='OK', max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Check'), ('SENSOR', 'IoT Sensor'), ('BLUETOOTH', 'Bluetooth Probe')], default='MANUAL', max_length=15)),
                ('recorded_by', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='inventory.storagelocation')),
            ],
            options={
                'verbose_name': 'Temperature Log',
                'verbose_name_plural': 'Temperature Logs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIVED', '📦 Received into storage'), ('MOVED', '🔄 Moved between locations'), ('FROZE', '🧊 Frozen'), ('THAW_QUEUED', '📋 Queued for thaw'), ('THAWING', '🔄 Thawing started'), ('THAW_COMPLETE', '✅ Thaw complete'), ('DISPLAYED', '🛒 Moved to display'), ('PULLED', '⏸️ Pulled from display'), ('REFREEZE', '🧊 Returned to freeze'), ('SOLD', '💰 Sold'), ('PROCESSED', '🔪 Processed'), ('DISCARDED', '🗑️ Discarded'), ('ADJUSTED', '⚖️ Weight/price adjusted')], max_length=20)),
                ('weight_at_movement', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Weight at time of movement (kg)', max_digits=6)),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='inventory.storagelocation')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.package')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.storagelocation')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='PriceChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('mode', models.CharField(default='manual', help_text='auto | price_per_kg | cost_margin | discount | manual', max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The value used in calculation', max_digits=10)),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='inventory.package')),
            ],
            options={
                'verbose_name': 'Price Change History',
                'verbose_name_plural': 'Price Change Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='package',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='BarcodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('supplier_id', models.PositiveIntegerField(default=0)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_sequences', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Barcode Sequence',
                'verbose_name_plural': 'Barcode Sequences',
                'unique_together': {('product', 'batch_number', 'supplier_id')},
            },
        ),
    ]
