# Generated by Django 4.1 on 2026-08-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='barcode',
        ),
    ]
