# Generated by Django 4.1 on 2026-08-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0002_remove_category_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_product',
            new_name='name_type',
        ),
    ]
