# Generated by Django 4.1 on 2026-08-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0004_supply_meat_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product_info',
            name='protent',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('mfg', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_meat.product_info')),
            ],
        ),
    ]
