# Generated by Django 4.1 on 2026-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0005_product_info_fat_product_info_protent_product_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='meat_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kcalories', models.FloatField(default=0)),
                ('protent', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_info',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='product_info',
            name='protent',
        ),
    ]
