# Generated by Django 4.1 on 2026-08-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0008_meat_parts_prefix_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='prefix_barcode',
        ),
    ]
