# Generated by Django 4.1 on 2026-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0009_remove_product_info_prefix_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='name',
        ),
        migrations.AddField(
            model_name='product_list',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
