# Generated by Django 4.1 on 2026-08-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0010_remove_product_list_name_product_list_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
