# Generated by Django 4.1 on 2026-08-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0015_product_list_loyverse_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='loyverse_variant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
