# Generated by Django 4.1 on 2026-08-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0016_product_list_loyverse_variant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyverseSyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product_list',
            name='loyverse_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_list',
            name='loyverse_sync_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock_meat.loyversesyncbatch'),
        ),
    ]
