# Generated by Django 4.1 on 2026-08-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0018_pricechangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat_parts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meat_parts', to='stock_meat.category'),
        ),
    ]
