# Generated by Django 4.1 on 2026-08-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0003_rename_name_product_category_name_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply_meat',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('name_place', models.CharField(max_length=20)),
                ('locations', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_barcode', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_meat.supply_meat')),
                ('type_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_meat.category')),
            ],
        ),
    ]
