# Generated by Django 4.1 on 2026-08-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0006_meat_parts_remove_product_info_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='barcode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_info',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_meat.meat_parts'),
        ),
    ]
