# Generated by Django 4.1 on 2026-08-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0007_product_list_barcode_alter_product_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat_parts',
            name='prefix_barcode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
