# Generated by Django 4.1 on 2026-08-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0011_alter_product_info_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='lot_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_products', to='stock_meat.product_info'),
        ),
    ]
