# Generated by Django 4.1 on 2026-08-14 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0012_product_info_lot_number_alter_product_info_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_meat.product_info'),
        ),
    ]
