# Generated by Django 4.1 on 2026-08-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0013_product_list_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='selling_price_per_kg',
            field=models.FloatField(default=0),
        ),
    ]
