# Generated by Django 4.1 on 2026-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0014_product_info_selling_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='loyverse_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_list',
            name='loyverse_sku',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product_list',
            name='loyverse_synced',
            field=models.BooleanField(default=False),
        ),
    ]
