# Generated by Django 4.1 on 2026-08-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0019_meat_parts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='display_max_days',
            field=models.PositiveIntegerField(default=3, help_text='วางขายได้สูงสุดกี่วัน'),
        ),
        migrations.AddField(
            model_name='product_info',
            name='entered_display_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_info',
            name='last_alert_at',
            field=models.DateTimeField(blank=True, help_text='แจ้งเตือนครั้งล่าสุดเมื่อไหร่', null=True),
        ),
        migrations.AddField(
            model_name='product_info',
            name='rotate_priority',
            field=models.PositiveIntegerField(default=0, help_text='ความสำคัญในการหมุนเวียน (สูง = หมุนก่อน)'),
        ),
        migrations.AddField(
            model_name='product_info',
            name='storage_status',
            field=models.CharField(choices=[('frozen', '❄️ แช่แข็ง'), ('thawing', '🔄 กำลังละลาย'), ('display', '🛒 วางขาย'), ('depleted', '📦 หมด')], default='frozen', max_length=20),
        ),
        migrations.AddField(
            model_name='product_info',
            name='thaw_duration_hours',
            field=models.PositiveIntegerField(default=24, help_text='เวลาละลาย (ชั่วโมง)'),
        ),
        migrations.AddField(
            model_name='product_info',
            name='thaw_queue_position',
            field=models.PositiveIntegerField(default=0, help_text='ลำดับในคิวละลาย (0 = ไม่ได้อยู่ในคิว)'),
        ),
        migrations.AddField(
            model_name='product_info',
            name='thaw_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FreezeRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('thaw_start', '🔄 เริ่มละลาย'), ('thaw_ready', '✅ ละลายเสร็จ'), ('display_start', '🛒 เริ่มวางขาย'), ('display_end', '⏸️ หยุดวางขาย'), ('freeze_return', '🧊 กลับแช่'), ('alert_sent', '🔔 ส่งแจ้งเตือน')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('weight_at_action', models.FloatField(default=0, help_text='น้ำหนัก ณ เวลาที่ทำรายการ')),
                ('status_before', models.CharField(blank=True, default='', max_length=20)),
                ('status_after', models.CharField(blank=True, default='', max_length=20)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_rotations', to='stock_meat.product_info')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
