# Generated by Django 4.2.30 on 2026-08-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0023_electricitybill_product_info_max_display_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productprocessing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50)),
                ('receipt_date', models.DateTimeField()),
                ('store_id', models.CharField(blank=True, default='', max_length=100)),
                ('loyverse_sku', models.CharField(max_length=40)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_percent', models.FloatField(default=0)),
                ('days_to_sell', models.IntegerField(default=0, help_text='จำนวนวันจาก mfg ถึงขาย')),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, help_text='ค่าไฟที่เสียไปกับชิ้นนี้', max_digits=10)),
                ('loyverse_item_id', models.CharField(blank=True, default='', max_length=100)),
                ('loyverse_variant_id', models.CharField(blank=True, default='', max_length=100)),
                ('loyverse_receipt_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to='stock_meat.product_list')),
            ],
            options={
                'ordering': ['-receipt_date'],
                'indexes': [models.Index(fields=['loyverse_sku'], name='stock_meat__loyvers_f5b0f7_idx'), models.Index(fields=['receipt_date'], name='stock_meat__receipt_816e00_idx'), models.Index(fields=['loyverse_receipt_id'], name='stock_meat__loyvers_e88853_idx')],
            },
        ),
    ]
