# Generated by Django 4.2.30 on 2026-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0024_solditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyElectricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, help_text='เลขมิเตอร์ ณ วันนั้น', max_digits=12, null=True)),
                ('units_used', models.DecimalField(decimal_places=2, default=0, help_text='หน่วยที่ใช้ในวันนั้น', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='ค่าไฟในวันนั้น (บาท)', max_digits=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=4.58, max_digits=6)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
