# Generated by Django 4.2.30 on 2026-08-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0025_daily_electricity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='freeze_end_at',
            field=models.DateTimeField(blank=True, help_text='เวลาที่คาดว่าแช่แข็งเสร็จ (ตั้งเอง)', null=True),
        ),
        migrations.AddField(
            model_name='product_list',
            name='freeze_target_temp',
            field=models.IntegerField(default=-8, help_text='อุณหภูมิเป้าหมายของตู้แช่ (°C)'),
        ),
    ]
