# Generated by Django 4.2.30 on 2026-08-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0026_add_freeze_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='freeze_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='ระยะเวลาแช่แข็งที่กำหนด (นาที)'),
        ),
        migrations.AddField(
            model_name='product_list',
            name='freeze_started_at',
            field=models.DateTimeField(blank=True, help_text='เวลาที่เริ่มแช่แข็ง', null=True),
        ),
    ]
