# Generated by Django 4.2.30 on 2026-08-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0027_add_freeze_started_and_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='thaw_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='เวลาที่เข้าคิวละลาย', null=True),
        ),
        migrations.AddField(
            model_name='product_list',
            name='thaw_target_ready_at',
            field=models.DateTimeField(blank=True, help_text='เวลาที่ต้องการให้ละลายเสร็จ (พร้อมจำหน่าย)', null=True),
        ),
    ]
