# Generated by Django 4.2.30 on 2026-08-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_meat', '0028_add_thaw_scheduling_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', '📋 วางแผน'), ('active', '🔄 กำลังดำเนินการ'), ('completed', '✅ เสร็จสิ้น'), ('cancelled', '❌ ยกเลิก')], default='planned', max_length=20)),
                ('target_ready_at', models.DateTimeField(help_text='เวลาที่ต้องการให้สินค้าพร้อมจำหน่าย')),
                ('thaw_start_at', models.DateTimeField(blank=True, help_text='เวลาที่ต้องเริ่มละลาย (คำนวณจาก target - thaw_duration - buffer)', null=True)),
                ('freeze_end_at', models.DateTimeField(blank=True, help_text='เวลาที่แช่แข็งเสร็จ (ต้องก่อน thaw_start)', null=True)),
                ('freeze_start_at', models.DateTimeField(blank=True, help_text='เวลาที่เริ่มแช่แข็ง', null=True)),
                ('freeze_duration_minutes', models.PositiveIntegerField(default=0, help_text='ระยะเวลาแช่แข็ง (นาที)')),
                ('thaw_duration_minutes', models.PositiveIntegerField(default=0, help_text='ระยะเวลาละลาย (นาที)')),
                ('buffer_minutes', models.PositiveIntegerField(default=120, help_text='เวลา buffer ก่อน ready (นาที)')),
                ('freeze_duration_estimated', models.PositiveIntegerField(default=0, help_text='เวลาแช่ประมาณ (นาที)')),
                ('thaw_duration_estimated', models.PositiveIntegerField(default=0, help_text='เวลาละลายประมาณ (นาที)')),
                ('is_override', models.BooleanField(default=False, help_text='True = ผู้ใช้แก้ไขเวลาเอง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_schedules', to='stock_meat.product_list')),
            ],
            options={
                'ordering': ['target_ready_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('freeze_start', '🧊 เริ่มแช่แข็ง'), ('freeze_check', '🔍 ตรวจสอบแช่'), ('thaw_queue', '📋 เข้าคิวละลาย'), ('thaw_start', '🔄 เริ่มละลาย'), ('thaw_check', '🔍 ตรวจสอบละลาย'), ('display_start', '🛒 นำออกวางขาย'), ('display_return', '🧊 นำกลับแช่')], max_length=20)),
                ('scheduled_at', models.DateTimeField(help_text='เวลาที่กำหนดให้ทำ')),
                ('status', models.CharField(choices=[('pending', '⏳ รอดำเนินการ'), ('in_progress', '🔄 กำลังทำ'), ('completed', '✅ เสร็จแล้ว'), ('skipped', '⏭️ ข้าม'), ('overdue', '🔴 เกินกำหนด')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotation_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='stock_meat.rotationschedule')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
