# Generated by Django 4.2.30 on 2026-08-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('FREEZE_START', 'Freeze Start'), ('FREEZE_CHECK', 'Freeze Check'), ('MOVE_TO_THAW_QUEUE', 'Move To Thaw Queue'), ('THAW_START', 'Thaw Start'), ('THAW_CHECK', 'Thaw Check'), ('THAW_COMPLETE', 'Thaw Complete'), ('MOVE_TO_DISPLAY', 'Move To Display'), ('REFREEZE', 'Refreeze'), ('PROCESS', 'Process'), ('DISCARD', 'Discard')], max_length=30)),
                ('scheduled_at', models.DateTimeField(help_text='When task should be performed')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_tasks', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_tasks', to='inventory.package')),
                ('rotation_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_tasks', to='planning.rotationplan')),
            ],
            options={
                'verbose_name': 'Worker Task',
                'verbose_name_plural': 'Worker Tasks',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.workertask')),
            ],
            options={
                'verbose_name': 'Task Event',
                'verbose_name_plural': 'Task Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RotationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_events', to='inventory.package')),
            ],
            options={
                'verbose_name': 'Rotation Event',
                'verbose_name_plural': 'Rotation Events',
                'ordering': ['timestamp'],
            },
        ),
    ]
