# Generated by Django 5.2.17 on 2026-08-25 08:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('target_temperature', models.DecimalField(decimal_places=2, help_text='Target temperature in Celsius', max_digits=5)),
                ('minimum_duration', models.DurationField(help_text='Minimum freeze duration')),
                ('default_duration', models.DurationField(help_text='Default freeze duration')),
                ('buffer_duration', models.DurationField(default=datetime.timedelta(0), help_text='Buffer time added to duration')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Freeze Profile',
                'verbose_name_plural': 'Freeze Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThawProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('default_duration', models.DurationField(help_text='Default thaw duration')),
                ('minimum_duration', models.DurationField(help_text='Minimum thaw duration')),
                ('buffer_duration', models.DurationField(default=datetime.timedelta(0), help_text='Buffer time added to duration')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thaw Profile',
                'verbose_name_plural': 'Thaw Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RotationPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_ready_at', models.DateTimeField(help_text='When package should be ready for sale')),
                ('planned_thaw_start_at', models.DateTimeField(help_text='Calculated thaw start time')),
                ('planned_thaw_queue_at', models.DateTimeField(help_text='When to add to thaw queue')),
                ('planned_freeze_start_at', models.DateTimeField(help_text='When to start freezing')),
                ('planned_freeze_end_at', models.DateTimeField(help_text='When freeze should complete')),
                ('freeze_duration', models.DurationField(help_text='Actual freeze duration used')),
                ('thaw_duration', models.DurationField(help_text='Actual thaw duration used')),
                ('freeze_override', models.DurationField(blank=True, help_text='Manual freeze duration override', null=True)),
                ('thaw_override', models.DurationField(blank=True, help_text='Manual thaw duration override', null=True)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('overridden_by', models.CharField(blank=True, default='', max_length=100)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('AT_RISK', 'At Risk'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freeze_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_plans', to='planning.freezeprofile')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_plan', to='inventory.package')),
                ('thaw_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_plans', to='planning.thawprofile')),
            ],
            options={
                'verbose_name': 'Rotation Plan',
                'verbose_name_plural': 'Rotation Plans',
                'ordering': ['target_ready_at'],
            },
        ),
        migrations.CreateModel(
            name='ThawQueueEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_position', models.PositiveIntegerField(help_text='Position in queue (1 = first)')),
                ('planned_start_at', models.DateTimeField(help_text='When thaw should start')),
                ('target_ready_at', models.DateTimeField(help_text='Target ready time')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('READY_TO_START', 'Ready To Start'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='thaw_queue_entry', to='inventory.package')),
                ('rotation_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='planning.rotationplan')),
            ],
            options={
                'verbose_name': 'Thaw Queue Entry',
                'verbose_name_plural': 'Thaw Queue Entries',
                'ordering': ['queue_position'],
            },
        ),
    ]
