# Generated by Django 5.2.17 on 2026-08-25 19:41

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thawprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'All Categories'), ('PORK', 'Pork'), ('CHICKEN', 'Chicken'), ('BEEF', 'Beef'), ('LAMB', 'Lamb'), ('FISH', 'Fish'), ('OTHER', 'Other')], default='', help_text='Product category this profile applies to (blank = all)', max_length=20),
        ),
        migrations.AddField(
            model_name='thawprofile',
            name='max_temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Maximum allowed thaw temperature in Celsius', max_digits=5),
        ),
        migrations.AddField(
            model_name='thawprofile',
            name='min_temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Minimum allowed thaw temperature in Celsius', max_digits=5),
        ),
        migrations.AddField(
            model_name='thawprofile',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Documentation of assumptions and basis for this profile'),
        ),
        migrations.AddField(
            model_name='thawprofile',
            name='target_temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Target thaw temperature in Celsius (e.g., 3°C for refrigerated thawing)', max_digits=5),
        ),
        migrations.AddField(
            model_name='thawprofile',
            name='thaw_capacity',
            field=models.PositiveIntegerField(default=20, help_text='Maximum concurrent thaw operations for this profile'),
        ),
        migrations.AddField(
            model_name='thawprofile',
            name='weight_scale_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.20'), help_text='Multiplier for duration when package exceeds 2× threshold (e.g., 1.20 = +20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='thawprofile',
            name='weight_threshold_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Weight (kg) at which minimum_duration transitions to default_duration', max_digits=6),
        ),
        migrations.AlterField(
            model_name='thawprofile',
            name='buffer_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Safety buffer added on top of calculated duration'),
        ),
        migrations.AlterField(
            model_name='thawprofile',
            name='default_duration',
            field=models.DurationField(help_text='Default thaw duration for packages above threshold weight'),
        ),
        migrations.AlterField(
            model_name='thawprofile',
            name='minimum_duration',
            field=models.DurationField(help_text='Minimum thaw duration for small packages'),
        ),
    ]
