# Generated by Django 4.2.30 on 2026-08-28 18:34

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_temperature', models.DecimalField(decimal_places=2, help_text='Target temperature (°C)', max_digits=5)),
                ('minimum_duration', models.DurationField(help_text='Minimum freeze duration')),
                ('default_duration', models.DurationField(help_text='Default freeze duration')),
                ('buffer_duration', models.DurationField(default=datetime.timedelta(0), help_text='Buffer time added to duration')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Freeze Profile',
                'verbose_name_plural': 'Freeze Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RotationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ready_at', models.DateTimeField(help_text='When package should be ready for sale')),
                ('planned_thaw_start_at', models.DateTimeField(help_text='Calculated thaw start time')),
                ('planned_thaw_queue_at', models.DateTimeField(help_text='When to add to thaw queue')),
                ('planned_freeze_start_at', models.DateTimeField(help_text='When to start freezing')),
                ('planned_freeze_end_at', models.DateTimeField(help_text='When freeze should complete')),
                ('freeze_duration', models.DurationField(help_text='Actual freeze duration used')),
                ('thaw_duration', models.DurationField(help_text='Actual thaw duration used')),
                ('freeze_override', models.DurationField(blank=True, help_text='Manual freeze override', null=True)),
                ('thaw_override', models.DurationField(blank=True, help_text='Manual thaw override', null=True)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('overridden_by', models.CharField(blank=True, default='', max_length=100)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('AT_RISK', 'At Risk'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=20)),
                ('legacy_rotation_schedule_id', models.PositiveIntegerField(blank=True, help_text='Reference to database_clmeat_main RotationSchedule.id', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freeze_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_plans', to='planning.freezeprofile')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_plan', to='inventory.package')),
            ],
            options={
                'verbose_name': 'Rotation Plan',
                'verbose_name_plural': 'Rotation Plans',
                'ordering': ['target_ready_at'],
            },
        ),
        migrations.CreateModel(
            name='ThawProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_duration', models.DurationField(help_text='Default thaw duration')),
                ('minimum_duration', models.DurationField(help_text='Minimum thaw duration')),
                ('buffer_duration', models.DurationField(default=datetime.timedelta(0), help_text='Safety buffer')),
                ('weight_threshold_kg', models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Weight (kg) where min→default transition occurs', max_digits=6)),
                ('weight_scale_factor', models.DecimalField(decimal_places=2, default=Decimal('1.20'), help_text='Multiplier for packages > 2× threshold', max_digits=5)),
                ('target_temperature', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Target thaw temperature (°C)', max_digits=5)),
                ('min_temperature', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('max_temperature', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('thaw_capacity', models.PositiveIntegerField(default=20)),
                ('category', models.CharField(blank=True, default='', help_text='Product category code (blank = all)', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thaw Profile',
                'verbose_name_plural': 'Thaw Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThawQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_position', models.PositiveIntegerField(help_text='Position in queue (1 = first)')),
                ('planned_start_at', models.DateTimeField(help_text='When thaw should start')),
                ('target_ready_at', models.DateTimeField(help_text='Target ready time')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('READY_TO_START', 'Ready To Start'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='thaw_queue_entry', to='inventory.package')),
                ('rotation_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='planning.rotationplan')),
            ],
            options={
                'verbose_name': 'Thaw Queue Entry',
                'verbose_name_plural': 'Thaw Queue Entries',
                'ordering': ['queue_position'],
            },
        ),
        migrations.AddField(
            model_name='rotationplan',
            name='thaw_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_plans', to='planning.thawprofile'),
        ),
    ]
