# Generated by Django 5.2.17 on 2026-08-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationplan',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_plans', to='inventory.package'),
        ),
        migrations.AlterField(
            model_name='thawqueueentry',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thaw_queue_entries', to='inventory.package'),
        ),
        migrations.CreateModel(
            name='RotationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(help_text='Cycle number for this package (1, 2, 3, ...)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('freeze_started_at', models.DateTimeField(blank=True, null=True)),
                ('freeze_completed_at', models.DateTimeField(blank=True, null=True)),
                ('thaw_started_at', models.DateTimeField(blank=True, null=True)),
                ('thaw_completed_at', models.DateTimeField(blank=True, null=True)),
                ('display_started_at', models.DateTimeField(blank=True, null=True)),
                ('display_ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('', 'Pending'), ('SOLD', 'Sold'), ('DISCARDED', 'Discarded'), ('REFROZEN', 'Refrozen'), ('CANCELLED', 'Cancelled')], default='', max_length=20)),
                ('outcome_reason', models.TextField(blank=True, default='')),
                ('outcome_actor', models.CharField(blank=True, default='', max_length=100)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_cycles', to='inventory.package')),
            ],
            options={
                'verbose_name': 'Rotation Cycle',
                'verbose_name_plural': 'Rotation Cycles',
                'ordering': ['package', 'cycle_number'],
                'unique_together': {('package', 'cycle_number')},
            },
        ),
        migrations.AddField(
            model_name='rotationplan',
            name='rotation_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='planning.rotationcycle'),
        ),
        migrations.AddField(
            model_name='thawqueueentry',
            name='rotation_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='planning.rotationcycle'),
        ),
    ]
