# Generated by Django 5.2.17 on 2026-08-31 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_add_rotation_cycle_and_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thaw_profile', models.OneToOneField(help_text='Profile whose capacity this lock serializes', on_delete=django.db.models.deletion.PROTECT, related_name='capacity_lock', to='planning.thawprofile')),
            ],
            options={
                'verbose_name': 'Capacity Lock',
                'verbose_name_plural': 'Capacity Locks',
            },
        ),
    ]
